package skills

const (
	AcrobaticsName             string = "Acrobatics"
	AppraiseName               string = "Appraise"
	BluffName                  string = "Bluff"
	ClimbName                  string = "Climb"
	CraftName                  string = "Craft"
	DiplomacyName              string = "Diplomacy"
	DisableDeviceName          string = "DisableDevice"
	DisguiseName               string = "Disguise"
	EscapeArtistName           string = "EscapeArtist"
	FlyName                    string = "Fly"
	HandleAnimalName           string = "HandleAnimal"
	HealName                   string = "Heal"
	IntimidateName             string = "Intimidate"
	KnowledgeArcanaName        string = "KnowledgeArcana"
	KnowledgeDungeoneeringName string = "KnowledgeDungeoneering"
	KnowledgeEngineeringName   string = "KnowledgeEngineering"
	KnowledgeGeographyName     string = "KnowledgeGeography"
	KnowledgeHistoryName       string = "KnowledgeHistory"
	KnowledgeLocalName         string = "KnowledgeLocal"
	KnowledgeNatureName        string = "KnowledgeNature"
	KnowledgeNobilityName      string = "KnowledgeNobility"
	KnowledgePlanesName        string = "KnowledgePlanes"
	KnowledgeReligionName      string = "KnowledgeReligion"
	LinguisticsName            string = "Linguistics"
	PerceptionName             string = "Perception"
	PerformName                string = "Perform"
	ProfessionName             string = "Profession"
	RideName                   string = "Ride"
	SenseMotiveName            string = "SenseMotive"
	SleightOfHandName          string = "SleightOfHand"
	SpellcraftName             string = "Spellcraft"
	StealthName                string = "Stealth"
	SurvivalName               string = "Survival"
	SwimName                   string = "Swim"
	UseMagicDeviceName         string = "UseMagicDevice"
)
